# Generated by Django 4.1 on 2022-08-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_rename_text_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='executor',
        ),
    ]
