# Generated by Django 4.0.4 on 2022-08-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='task_manager.label'),
        ),
    ]
