# Generated by Django 4.0.4 on 2022-08-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_tasklabel_task_labels_tasklabel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task'),
        ),
    ]
