# Generated by Django 4.0.4 on 2022-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_tasklabel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task_manager.TaskLabel', to='task_manager.label'),
        ),
    ]
