name: lint & test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run:  |
          pip install poetry
          poetry env use 3.8
          make install
      - name: lint
        run: make lint
